
// This is an autogenerated file from Firebase Studio.
"use client";
import React from "react";
import { HeroParallax } from "@/components/ui/hero-parallax";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { ArrowRight } from "lucide-react";

const heroProducts = [
    {
    title: "AURA Wireless Headphones",
    link: "/store",
    thumbnail:
      "https://images.unsplash.com/photo-1505740420928-5e560c06d76e?q=80&w=2070&auto=format&fit=crop",
  },
  {
    title: "ChronoLink Smartwatch",
    link: "/store",
    thumbnail:
      "https://images.unsplash.com/photo-1546868871-7041f2a55e12?q=80&w=1964&auto=format&fit=crop",
  },
    {
    title: "ErgoFlow Mouse",
    link: "/store",
    thumbnail:
      "https://images.unsplash.com/photo-1629429408209-1f9122651535?q=80&w=2070&auto=format&fit=crop",
  },
  {
    title: "Pixel Perfect",
    link: "/store",
    thumbnail:
      "https://aceternity.com/images/products/thumbnails/new/pixelperfect.png",
  },

  {
    title: "Algochurn",
    link: "/store",
    thumbnail:
      "https://aceternity.com/images/products/thumbnails/new/algochurn.png",
  },
    {
    title: "VoltPack Power Bank",
    link: "/store",
    thumbnail:
      "https://images.unsplash.com/photo-1588872657577-19d15d85ab28?q=80&w=2070&auto=format&fit=crop",
  },
  {
    title: "Aceternity UI",
    link: "/store",
    thumbnail:
      "https://aceternity.com/images/products/thumbnails/new/aceternityui.png",
  },
  {
    title: "Tailwind Master Kit",
    link: "/store",
    thumbnail:
      "https://aceternity.com/images/products/thumbnails/new/tailwindmasterkit.png",
  },
    {
    title: "Arctic Insulated Tumbler",
    link: "/store",
    thumbnail:
      "https://images.unsplash.com/photo-1559863345-0263b455c913?q=80&w=1887&auto=format&fit=crop",
  },
  {
    title: "SmartBridge",
    link: "/store",
    thumbnail:
      "https://aceternity.com/images/products/thumbnails/new/smartbridge.png",
  },
  {
    title: "Renderwork Studio",
    link: "/store",
    thumbnail:
      "https://aceternity.com/images/products/thumbnails/new/renderwork.png",
  },

  {
    title: "Creme Digital",
    link: "/store",
    thumbnail:
      "https://aceternity.com/images/products/thumbnails/new/cremedigital.png",
  },
  {
    title: "Golden Bells Academy",
    link: "/store",
    thumbnail:
      "https://aceternity.com/images/products/thumbnails/new/goldenbellsacademy.png",
  },

  {
    title: "Invoker Labs",
    link: "/store",
    thumbnail:
      "https://aceternity.com/images/products/thumbnails/new/invoker.png",
  },
  {
    title: "E Free Invoice",
    link: "/store",
    thumbnail:
      "https://aceternity.com/images/products/thumbnails/new/efreeinvoice.png",
  },
];


export default function LandingPage() {
  return (
    <div className="bg-background min-h-screen">
      <HeroParallax products={heroProducts} />
      <div className="container mx-auto px-4 py-20 md:py-32 text-center">
         <h2 className="text-3xl md:text-5xl font-bold text-foreground mb-4">Ready to Shop Smarter?</h2>
         <p className="text-lg md:text-xl text-muted-foreground max-w-3xl mx-auto mb-8">
            Our full collection is waiting for you. Browse our curated selection of high-quality goods, manage your cart, and get AI-powered recommendations.
         </p>
         <Link href="/store">
            <Button size="lg" className="text-lg">
                Explore The Store <ArrowRight className="ml-2 h-5 w-5" />
            </Button>
         </Link>
      </div>
    </div>
  );
}
