// This is an autogenerated file from Firebase Studio.
"use client";

import { ScanLine, ShoppingCart, QrCode, User } from "lucide-react";
import type { FC } from "react";
import Link from 'next/link';
import { ThemeToggle } from "./theme-toggle";
import { Button } from "./ui/button";

interface HeaderProps {
  cartCount: number;
}

const Header: FC<HeaderProps> = ({ cartCount }) => {
  return (
    <header className="sticky top-0 z-40 w-full border-b bg-background/95 backdrop-blur-sm">
      <div className="container mx-auto flex h-16 items-center justify-between px-4 md:px-6">
        <Link href="/" className="flex items-center gap-2">
          <ScanLine className="h-8 w-8 text-primary" />
          <h1 className="text-2xl font-bold text-primary">ScanGo</h1>
        </Link>
        <div className="flex items-center gap-2 sm:gap-4">
          <Link href="/scan">
            <Button variant="outline" className="gap-2">
              <QrCode className="h-5 w-5"/>
              <span className="hidden sm:inline">Scan</span>
            </Button>
          </Link>
          <ThemeToggle />
          <Link href="/login">
            <Button variant="ghost" size="icon">
              <User className="h-6 w-6" />
              <span className="sr-only">Admin Login</span>
            </Button>
          </Link>
          <div className="relative">
            <ShoppingCart className="h-7 w-7 text-muted-foreground transition-colors hover:text-foreground" />
            {cartCount > 0 && (
              <span className="absolute -right-2 -top-2 flex h-5 w-5 items-center justify-center rounded-full bg-primary text-xs font-bold text-primary-foreground">
                {cartCount}
              </span>
            )}
          </div>
        </div>
      </div>
    </header>
  );
};

export default Header;
